language: csharp
mono:
 - beta
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libunwind8
install:
  - uname -a
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh
  - source ~/.dnx/dnvm/dnvm.sh
  - dnvm install 1.0.0-rc1-update2 -r coreclr -arch x64

script:
  - dnu restore
  - ./build-all.sh
  - ./run-tests.sh
