dist: trusty

language: csharp
mono: latest
dotnet: 2.0.2

# Needed by GitVersion
git:
  depth: 9999999

branches:
  only:
    - develop
    - release/v1.2
    - master

addons:
  apt:
    packages:
    - jq

script:
  - ./build-ci.sh
