dist: trusty

language: csharp
mono: latest
dotnet: 2.0.2

# Needed by GitVersion
git:
  depth: 9999999

branches:
  only:
    - development/v1.1
    - release/v1.1

addons:
  apt:
    packages:
    - jq

script:
  - ./build-ci.sh
