language: csharp
mono: latest
dotnet: 2.0.0
dist: trusty

branches:
  only:
    - development/v1.1
    - release/v1.1

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - jq
    - dotnet-sdk-2.0.2

script:
  - ./build-ci.sh
