branches:
  only:
    - development/r1.0
    - release/r1.0

language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      env:
        - HTTPLEASE_BUILD_VERSION="alpha2"
        - DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=798405 # v1.0.0-preview1
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      env:
        - HTTPLEASE_BUILD_VERSION="alpha2"
        - DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=798404 # v1.0.0-preview1

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force openssl ; fi

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
  - mkdir -p "$DOTNET_INSTALL_DIR"
  - curl -L "$DOTNET_SDK_URL" | tar -xzv -C "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

script:
  - dotnet --info
  - echo 'dotnet restore' && echo -en 'travis_fold:start:dotnet_restore'
  - ./restore-packages.sh
  - echo -en 'travis_fold:end:dotnet_restore'
  - echo 'dotnet build' && echo -en 'travis_fold:start:dotnet_build'
  - ./build-all.sh
  - echo -en 'travis_fold:end:dotnet_build'
  - echo 'dotnet build' && echo -en 'travis_fold:start:dotnet_test'
  - ./run-tests.sh
  - echo -en 'travis_fold:end:dotnet_test'
  - ./package-all.sh
