version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2015
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps:
    dotnet restore

    $buildVersion = "beta2-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"
    
    dotnet build --version-suffix $buildVersion "src/HTTPlease*/project.json" "test/HTTPlease*/project.json"

test_script:
- ps: >-
    Dir test/HTTPlease* -Directory | % { dotnet test $_ }

deploy_script:
- ps: >-
    $buildVersion = "beta2-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"

    Dir src/VersionManagement* -Directory | % { dotnet pack --version-suffix $buildVersion $_ }

artifacts:
- path: src\artifacts\packages\*.nupkg

deploy:
  provider: NuGet
  on:
    branch: release/r1.0
  api_key:
    secure: ljl/r7XeQm+KBzR7pm1OOW4+YcDUsYiWlr9jWFztMh/8/orG4V9ylTi+P1jGME7g
  skip_symbols: false
  artifact: /.*\.nupkg$/
