version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2015
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

    dnvm install 1.0.0-rc1-update1 -r coreclr -arch x64
cache: C:\Users\appveyor\.dnx\packages
build_script:
- cmd: >-
    dnvm use 1.0.0-rc1-update1 -r coreclr -arch x64

    dnu -p src\HTTPlease build
test_script:
- cmd: dnx -p test\HTTPlease.Tests test
deploy_script:
- cmd: dnu -p src\HTTPlease package
