branches:
  only:
  - develop
  - release/v1.2
  - master

image: Visual Studio 2017

build_script:
- ps: .\build-ci.ps1

test_script:
- ps: .\test-ci.ps1

artifacts:
- path: src\artifacts\packages\*.nupkg

deploy:
  # MyGet feed (unstable)
  - provider: NuGet
    server: https://www.myget.org/F/httplease/api/v2/package
    symbol_server: https://www.myget.org/F/httplease/symbols/api/v2/package
    api_key:
      secure: FIA0E1YzvgpRKQTPH+ky8bh2wYBcyHiO/XINMQl8KoXpqpGLTX95bslkR1mspq/I
    skip_symbols: false
    artifact: /.*\.nupkg$/
    on:
      # Development branch or feature branch.
      branch: /(develop|development|feature)(\/)?.*/

  # MyGet feed (stable)
  - provider: NuGet
    server: https://www.myget.org/F/httplease/api/v2/package
    symbol_server: https://www.myget.org/F/httplease/symbols/api/v2/package
    api_key:
      secure: FIA0E1YzvgpRKQTPH+ky8bh2wYBcyHiO/XINMQl8KoXpqpGLTX95bslkR1mspq/I
    skip_symbols: false
    artifact: /.*\.nupkg$/
    on:
      # Release branch or master branch (only if tagged).
      branch: /(release|master)(\/)?.*/
      appveyor_repo_tag: true

  # Public feed
  - provider: NuGet
    api_key:
      secure: ljl/r7XeQm+KBzR7pm1OOW4+YcDUsYiWlr9jWFztMh/8/orG4V9ylTi+P1jGME7g
    skip_symbols: false
    artifact: /.*\.nupkg$/
    on:
      # Release branch or master branch (only if tagged).
      branch: /(release|master)(\/)?.*/
      appveyor_repo_tag: true
