version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2015
install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps: >-
    .\restore-packages.ps1

    $buildVersion = "alpha1-$env:APPVEYOR_BUILD_NUMBER"
    
    .\build-all.ps1 -BuildVersion $buildVersion

    .\package-all.ps1 -BuildVersion $buildVersion
artifacts:
- path: src\artifacts\packages\Debug\*.nupkg
test_script:
- ps: >-
    .\run-tests.ps1 -BuildVersion
