version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2015
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps: >-
    .\restore-packages.ps1

    $buildVersion = "beta1-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"
    
    .\build-all.ps1 -BuildVersion $buildVersion

    .\package-all.ps1 -BuildVersion $buildVersion
artifacts:
- path: src\artifacts\packages\*.nupkg
test_script:
- ps: >-
    .\run-tests.ps1 -BuildVersion
deploy:
  provider: NuGet
  on:
    branch: release/r1.0
  api_key:
    secure: ljl/r7XeQm+KBzR7pm1OOW4+YcDUsYiWlr9jWFztMh/8/orG4V9ylTi+P1jGME7g
  skip_symbols: false
  artifact: /.*\.nupkg/
