version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2017 RC
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps: .\build-ci.ps1

test_script:
- ps: .\test-ci.ps1

artifacts:
- path: src\artifacts\packages\*.nupkg

deploy:
  provider: NuGet
  on:
    branch: release/r1.0
  api_key:
    secure: ljl/r7XeQm+KBzR7pm1OOW4+YcDUsYiWlr9jWFztMh/8/orG4V9ylTi+P1jGME7g
  skip_symbols: false
  artifact: /.*\.nupkg$/
