version: 1.1.{build}

branches:
  only:
  - development/v1.1
  - release/v1.1

image: Visual Studio 2017
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps: .\build-ci.ps1

test_script:
- ps: .\test-ci.ps1

artifacts:
- path: src\artifacts\packages\*.nupkg

deploy:
  provider: NuGet
  on:
    branch: release/v1.1
  api_key:
    secure: ljl/r7XeQm+KBzR7pm1OOW4+YcDUsYiWlr9jWFztMh/8/orG4V9ylTi+P1jGME7g
  skip_symbols: false
  artifact: /.*\.nupkg$/
